name: TikTok Hashtag Pipeline

on:
  schedule:
    - cron: "0 */4 * * *"   # runs every 4 hours
  workflow_dispatch:        # allows manual run from GitHub UI

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pipeline script
      run: |
        python main_pipeline.py

    - name: Commit database back to repo
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add tiktok_data.db
        git commit -m "Update database [skip ci]" || echo "No changes"
        git push
