name: TikTok Hashtag Pipeline

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  pages: write
  id-token: write

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: false

    - name: Cache Hugging Face models
      uses: actions/cache@v3
      with:
        path: ~/.cache/huggingface
        key: ${{ runner.os }}-huggingface-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-huggingface-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
        pip install playwright

    - name: Install Playwright browsers
      run: |
        python -m playwright install chromium

    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "mryeje@gmail.com"

    - name: Run main pipeline
      run: python main_pipeline.py
      env:
        TOKENIZERS_PARALLELISM: "false"

    - name: Generate dashboard
      run: python Hastag-Dashboard-AIO.py

    - name: Prepare docs for GitHub Pages
      run: |
        mkdir -p docs/dashboard_assets
        cp tiktok_dashboard.html docs/index.html
        cp dashboard_assets/*.png docs/dashboard_assets/ 2>/dev/null || echo "No PNG files found in dashboard_assets"
        cp -r dashboard_assets/* docs/dashboard_assets/ 2>/dev/null || echo "No dashboard_assets directory found"

    - name: Pull latest changes
      run: |
        git fetch origin
        git reset --hard origin/main

    - name: Commit and push results
      if: success()
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"
        git add hashtags.db *.csv *.txt pipeline.log hashtags_with_relevance.csv docs dashboard_assets || true
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update: Pipeline results $(date -u +'%Y-%m-%d %H:%M')"
          git push origin main
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pipeline-results
        path: |
          *.png
          *.csv
          *.html
          *.txt
          pipeline.log
          hashtags.db
          hashtags_with_relevance.csv
          dashboard_assets

  deploy-pages:
    needs: run-pipeline
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
        
    - name: Download pipeline artifacts
      uses: actions/download-artifact@v4
      with:
        name: pipeline-results
        path: .
        
    - name: Prepare docs for GitHub Pages
      run: |
        mkdir -p docs/dashboard_assets
        # Try both possible dashboard filenames
        cp tiktok_dashboard.html docs/index.html 2>/dev/null || 
        cp hashtag_dashboard.html docs/index.html 2>/dev/null || 
        echo "Dashboard HTML not found, will use whatever is available"
        cp dashboard_assets/*.png docs/dashboard_assets/ 2>/dev/null || echo "No PNG files found in dashboard_assets"
        cp -r dashboard_assets/* docs/dashboard_assets/ 2>/dev/null || echo "No dashboard_assets directory found"
        
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
