name: TikTok Hashtag Pipeline

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Cache Hugging Face models
      uses: actions/cache@v3
      with:
        path: ~/.cache/huggingface
        key: ${{ runner.os }}-huggingface-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-huggingface-
          
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install playwright
        
    - name: Install Playwright browsers
      run: |
        python -m playwright install chromium
        
    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        
    - name: Run main pipeline
      run: python main_pipeline.py
      env:
        TOKENIZERS_PARALLELISM: "false"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pipeline-results
        path: |
          *.png
          *.csv
          *.html
          *.txt
          pipeline.log
          hashtags.db
          hashtags_with_relevance.csv